import math


def math_doc():
    """
    doc of methods in math
    """
    print('=====' + math.acos.__doc__ + '\n\n\n')
    print('=====' + math.acosh.__doc__ + '\n\n\n')
    print('=====' + math.asin.__doc__ + '\n\n\n')
    print('=====' + math.asinh.__doc__ + '\n\n\n')
    print('=====' + math.atan.__doc__ + '\n\n\n')
    print('=====' + math.atan2.__doc__ + '\n\n\n')
    print('=====' + math.atanh.__doc__ + '\n\n\n')
    print('=====' + math.ceil.__doc__ + '\n\n\n')
    print('=====' + math.copysign.__doc__ + '\n\n\n')
    print('=====' + math.cos.__doc__ + '\n\n\n')
    print('=====' + math.cosh.__doc__ + '\n\n\n')
    print('=====' + math.degrees.__doc__ + '\n\n\n')
    print('=====' + math.e.__doc__ + '\n\n\n')
    print('=====' + math.erf.__doc__ + '\n\n\n')
    print('=====' + math.erfc.__doc__ + '\n\n\n')
    print('=====' + math.exp.__doc__ + '\n\n\n')
    print('=====' + math.expm1.__doc__ + '\n\n\n')
    print('=====' + math.fabs.__doc__ + '\n\n\n')
    print('=====' + math.floor.__doc__ + '\n\n\n')
    print('=====' + math.fmod.__doc__ + '\n\n\n')
    print('=====' + math.frexp.__doc__ + '\n\n\n')
    print('=====' + math.fsum.__doc__ + '\n\n\n')
    print('=====' + math.gamma.__doc__ + '\n\n\n')
    print('=====' + math.gcd.__doc__ + '\n\n\n')
    print('=====' + math.hypot.__doc__ + '\n\n\n')
    print('=====' + math.inf.__doc__ + '\n\n\n')
    print('=====' + math.isclose.__doc__ + '\n\n\n')
    print('=====' + math.isfinite.__doc__ + '\n\n\n')
    print('=====' + math.isinf.__doc__ + '\n\n\n')
    print('=====' + math.isnan.__doc__ + '\n\n\n')
    print('=====' + math.ldexp.__doc__ + '\n\n\n')
    print('=====' + math.lgamma.__doc__ + '\n\n\n')
    print('=====' + math.log.__doc__ + '\n\n\n')
    print('=====' + math.log10.__doc__ + '\n\n\n')
    print('=====' + math.log1p.__doc__ + '\n\n\n')
    print('=====' + math.log2.__doc__ + '\n\n\n')
    print('=====' + math.modf.__doc__ + '\n\n\n')
    print('=====' + math.nan.__doc__ + '\n\n\n')
    print('=====' + math.pi.__doc__ + '\n\n\n')
    print('=====' + math.pow.__doc__ + '\n\n\n')
    print('=====' + math.radians.__doc__ + '\n\n\n')
    print('=====' + math.sin.__doc__ + '\n\n\n')
    print('=====' + math.sinh.__doc__ + '\n\n\n')
    print('=====' + math.sqrt.__doc__ + '\n\n\n')
    print('=====' + math.tan.__doc__ + '\n\n\n')
    print('=====' + math.tanh.__doc__ + '\n\n\n')
    print('=====' + math.tau.__doc__ + '\n\n\n')
    print('=====' + math.trunc.__doc__ + '\n\n\n')


if __name__ == '__main__':
    math_doc()
